apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: serving-helloworld-pipeline
spec:
  workspaces:
    - name: source
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision to check out
      default: main
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: "latest"
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
    - name: build-and-push-image
      taskRef:
        name: kaniko
        kind: Task
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: source
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)
    - name: update-manifest
      taskRef:
        name: yq
        kind: Task
      runAfter:
        - build-and-push-image
      workspaces:
        - name: source
          workspace: source
      params:
        - name: SCRIPT
          value: |
            /usr/bin/yq eval -i ".spec.template.spec.containers.[].image = \"$(tasks.build-and-push-image.results.IMAGE_URL)@$(tasks.build-and-push-image.results.IMAGE_DIGEST)\"" $(params.pathToYamlFile)
    - name: deploy-service
      taskRef:
        name: kn
        kind: Task
      runAfter:
        - update-manifest
      workspaces:
        - name: source
          workspace: source
      params:
      - name: ARGS
        value:
          - "service"
          - "apply"
          - "serving-helloworld"
          - "--filename"
          - "$(params.pathToYamlFile)"
          - "--env"
          - "IMAGE=$(tasks.build-and-push-image.results.IMAGE_URL)@$(tasks.build-and-push-image.results.IMAGE_DIGEST)"
          - "--image"
          - "$(tasks.build-and-push-image.results.IMAGE_URL)@$(tasks.build-and-push-image.results.IMAGE_DIGEST)"
